"use client";

import { useEffect, useRef, useState } from "react";

/** Remembers that this browser has read the notice. Not personal data - a flag. */
const SEEN = "artifinancial:notice-seen:v1";

/**
 * What this terminal is, said before it is used.
 *
 * The screen behind this shows real ticker symbols at realistic prices next to a
 * word that reads LIVE. Nothing about it is real: the prices come from a random
 * walk, the cash is imaginary, there is no broker and no model. Somebody landing
 * here without that context could screenshot a number and believe it was a quote,
 * and that is the one way a portfolio piece about markets can actually do harm.
 *
 * So it is stated plainly, once, up front. Do not remove it to make the demo
 * look more impressive.
 */
export function SimulatedNotice() {
  // Closed on first paint so a returning visitor never sees it flash.
  const [open, setOpen] = useState(false);
  const dialog = useRef<HTMLDivElement>(null);
  const confirm = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    try {
      if (!localStorage.getItem(SEEN)) setOpen(true);
    } catch {
      // Storage blocked. Showing it every visit is the safe way to be wrong.
      setOpen(true);
    }
  }, []);

  function dismiss() {
    setOpen(false);
    try {
      localStorage.setItem(SEEN, "1");
    } catch {
      // It will show again next visit, which is harmless.
    }
  }

  useEffect(() => {
    if (!open) return;
    confirm.current?.focus();

    function onKey(event: KeyboardEvent) {
      if (event.key === "Escape") {
        dismiss();
        return;
      }
      if (event.key !== "Tab" || !dialog.current) return;
      // Keep Tab inside the dialog, or focus wanders into the terminal behind
      // where a screen-reader user has no idea a dialog is open.
      const focusable = dialog.current.querySelectorAll<HTMLElement>("a[href], button");
      const first = focusable[0];
      const last = focusable[focusable.length - 1];
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    }

    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-void/85 px-4 py-8">
      <div
        ref={dialog}
        role="dialog"
        aria-modal="true"
        aria-labelledby="simulated-notice-title"
        className="max-h-full w-full max-w-lg overflow-y-auto rounded-panel border border-edge-hi bg-panel px-6 py-6"
      >
        <p className="text-[10px] tracking-[0.25em] text-accent uppercase">Simulated market</p>
        <p className="mt-1 text-[10px] tracking-[0.12em] text-ink-faint uppercase">
          Portfolio demo by J. Hubbers &middot; August 2026
        </p>
        <h2
          id="simulated-notice-title"
          className="mt-2 font-sans text-[19px] leading-tight font-semibold text-ink"
        >
          Nothing here is real money or real market data
        </h2>

        <div className="mt-4 space-y-3 text-[12px] leading-relaxed text-ink-dim">
          <p>
            Every price on this screen is generated by a random walk running in
            your browser. The tickers are real companies, the numbers are not
            their prices, and nothing is a quote. Do not use any figure here for
            anything.
          </p>
          <p>
            The <span className="text-ink">$10,000</span> is imaginary, there is
            no broker, and no order reaches a market. The assistant is a scripted
            mock, not a language model, and labels itself as one in every reply.
          </p>
          <p>
            Artifinancial is a portfolio project demonstrating a full trading
            workstation. Your positions are kept in this browser only and are
            visible to nobody else.
          </p>
        </div>

        <button
          ref={confirm}
          type="button"
          onClick={dismiss}
          className="mt-6 w-full rounded-panel border border-submit bg-submit px-4 py-2.5 text-[12px] tracking-[0.1em] text-ink uppercase"
        >
          Understood, open the terminal
        </button>
      </div>
    </div>
  );
}

/** The same fact, kept in the chrome once the dialog is gone. */
export function SimulatedBadge() {
  return (
    <span className="flex items-baseline gap-2">
      <span
        className="border border-accent/40 px-1.5 py-0.5 text-[9px] tracking-[0.15em] text-accent uppercase"
        title="Prices are generated by a simulator. No real money, no market data."
      >
        Simulated
      </span>
      <span className="hidden text-[9px] tracking-[0.12em] text-ink-faint uppercase lg:inline">
        Portfolio demo by J. Hubbers &middot; August 2026
      </span>
    </span>
  );
}
